# Site settings
title: Ashutosh Rishi Ranjan
email: ashutoshrishi92@gmail.com
description:
  "This is a blog on Programming and ideas linking everything
  in this world, expressed by me. I love diving into new languages and
  libraries and then write about them. I hope it's an enjoyable adventure."
baseurl: ""
url: "http://ashutoshrishi.com"
twitter_username: ashutoshrishi
github_username:  ashutoshrishi

# Build settings
markdown: kramdown
permalink: pretty


